import { Ingredient } from '../models/Ingredient.ts';

const INGREDIENTS: Ingredient[] = [
  {
    id: 1,
    name: 'Carrot',
    type: 'VEGETABLE',
    protein: 1.0,
    fat: 0.2,
    carbs: 9.6,
    sugar: 4.7,
    image: '/images/carrot.jpg',
  },
  {
    id: 2,
    name: 'Chicken Breast',
    type: 'MEAT',
    protein: 31.0,
    fat: 3.6,
    carbs: 0.0,
    sugar: 0.0,
    image: '/images/chicken_breast.jpg',
  },
  {
    id: 3,
    name: 'Broccoli',
    type: 'VEGETABLE',
    protein: 2.8,
    fat: 0.4,
    carbs: 6.6,
    sugar: 1.7,
    image: '/images/broccoli.jpg',
  },
  {
    id: 4,
    name: 'Salmon',
    type: 'FISH',
    protein: 20.0,
    fat: 13.0,
    carbs: 0.0,
    sugar: 0.0,
    image: '/images/salmon.jpg',
  },
  {
    id: 5,
    name: 'Apple',
    type: 'FRUIT',
    protein: 0.5,
    fat: 0.3,
    carbs: 25.0,
    sugar: 19.0,
    image: '/images/apple.jpg',
  },
  {
    id: 6,
    name: 'Banana',
    type: 'FRUIT',
    protein: 1.3,
    fat: 0.3,
    carbs: 27.0,
    sugar: 14.0,
    image: '/images/banana.jpg',
  },
  {
    id: 7,
    name: 'Spinach',
    type: 'VEGETABLE',
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    sugar: 0.4,
    image: '/images/spinach.jpg',
  },
  {
    id: 8,
    name: 'Sweet Potato',
    type: 'VEGETABLE',
    protein: 2.0,
    fat: 0.1,
    carbs: 20.0,
    sugar: 4.2,
    image: '/images/sweet_potato.jpg',
  },
  {
    id: 9,
    name: 'Avocado',
    type: 'FRUIT',
    protein: 2.0,
    fat: 15.0,
    carbs: 9.0,
    sugar: 0.7,
    image: '/images/avocado.jpg',
  },
  {
    id: 10,
    name: 'Eggs',
    type: 'DAIRY',
    protein: 6.0,
    fat: 5.0,
    carbs: 1.0,
    sugar: 0.5,
    image: '/images/eggs.jpg',
  },
  {
    id: 11,
    name: 'Greek Yogurt',
    type: 'DAIRY',
    protein: 10.0,
    fat: 0.4,
    carbs: 4.0,
    sugar: 3.0,
    image: '/images/greek_yogurt.jpg',
  },
  {
    id: 12,
    name: 'Cucumber',
    type: 'VEGETABLE',
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    sugar: 1.7,
    image: '/images/cucumber.jpg',
  },
  {
    id: 13,
    name: 'Tomato',
    type: 'VEGETABLE',
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    sugar: 2.6,
    image: '/images/tomato.jpg',
  },
  {
    id: 14,
    name: 'Lentils',
    type: 'LEGUME',
    protein: 9.0,
    fat: 0.4,
    carbs: 20.0,
    sugar: 1.8,
    image: '/images/lentils.jpg',
  },
  {
    id: 15,
    name: 'Almonds',
    type: 'NUT',
    protein: 21.0,
    fat: 49.0,
    carbs: 22.0,
    sugar: 3.9,
    image: '/images/almonds.jpg',
  },
  {
    id: 16,
    name: 'Peanut Butter',
    type: 'NUT',
    protein: 8.0,
    fat: 16.0,
    carbs: 6.0,
    sugar: 3.0,
    image: '/images/peanut_butter.jpg',
  },
  {
    id: 17,
    name: 'Olive Oil',
    type: 'OIL',
    protein: 0.0,
    fat: 14.0,
    carbs: 0.0,
    sugar: 0.0,
    image: '/images/olive_oil.jpg',
  },
  {
    id: 18,
    name: 'Beef',
    type: 'MEAT',
    protein: 26.0,
    fat: 20.0,
    carbs: 0.0,
    sugar: 0.0,
    image: '/images/beef.jpg',
  },
  {
    id: 19,
    name: 'Pork',
    type: 'MEAT',
    protein: 25.0,
    fat: 17.0,
    carbs: 0.0,
    sugar: 0.0,
    image: '/images/pork.jpg',
  },
  {
    id: 20,
    name: 'Tofu',
    type: 'TOFU',
    protein: 8.0,
    fat: 4.0,
    carbs: 2.0,
    sugar: 0.5,
    image: '/images/tofu.jpg',
  },
  {
    id: 21,
    name: 'Chickpeas',
    type: 'LEGUME',
    protein: 9.0,
    fat: 3.0,
    carbs: 27.0,
    sugar: 4.0,
    image: '/images/chickpeas.jpg',
  },
  {
    id: 22,
    name: 'Zucchini',
    type: 'VEGETABLE',
    protein: 1.2,
    fat: 0.3,
    carbs: 3.1,
    sugar: 2.5,
    image: '/images/zucchini.jpg',
  },
  {
    id: 23,
    name: 'Mushrooms',
    type: 'VEGETABLE',
    protein: 3.0,
    fat: 0.3,
    carbs: 3.3,
    sugar: 2.3,
    image: '/images/mushrooms.jpg',
  },
  {
    id: 24,
    name: 'Potato',
    type: 'VEGETABLE',
    protein: 2.0,
    fat: 0.2,
    carbs: 17.0,
    sugar: 0.8,
    image: '/images/potato.jpg',
  },
  {
    id: 25,
    name: 'Cauliflower',
    type: 'VEGETABLE',
    protein: 1.9,
    fat: 0.3,
    carbs: 5.0,
    sugar: 1.9,
    image: '/images/cauliflower.jpg',
  },
  {
    id: 26,
    name: 'Strawberries',
    type: 'FRUIT',
    protein: 0.8,
    fat: 0.3,
    carbs: 7.7,
    sugar: 4.9,
    image: '/images/strawberries.jpg',
  },
  {
    id: 27,
    name: 'Pineapple',
    type: 'FRUIT',
    protein: 0.5,
    fat: 0.1,
    carbs: 22.0,
    sugar: 16.0,
    image: '/images/pineapple.jpg',
  },
  {
    id: 28,
    name: 'Watermelon',
    type: 'FRUIT',
    protein: 0.6,
    fat: 0.2,
    carbs: 7.6,
    sugar: 6.2,
    image: '/images/watermelon.jpg',
  },
  {
    id: 29,
    name: 'Coconut',
    type: 'FRUIT',
    protein: 3.3,
    fat: 33.5,
    carbs: 15.2,
    sugar: 6.2,
    image: '/images/coconut.jpg',
  },
];

export default INGREDIENTS;
